### ISSUE TITLE
There was a error when i downloaded the plugins into the plugin folder

### ISSUE THREAD

**Issue by Jizzy015** [mack/magic-upload#6]
it could not be fired cuz
TypeError: Cannot read property 'subscribe' of undefined
    at new w (betterdiscord://plugins/MagicUpload.plugin.js:9:245)
    at Object.load (betterdiscord://plugins/MagicUpload.plugin.js:9:9437)
    at Object.initializeAddon (<anonymous>:4:42101)
    at Object.loadAddon (<anonymous>:4:8923)
    at Object.loadAddon (<anonymous>:4:40648)
    at Object.loadAllAddons (<anonymous>:4:11117)
    at Object.initialize (<anonymous>:4:5811)
    at Object.initialize (<anonymous>:4:39851)
    at Object.startup (<anonymous>:4:374576)

**Comment by Jizzy015** [comment]
how to solve it?

**Comment by mack** [comment]
Did you download this from the `releases` page? I haven't released the latest version yet, where I believe this bug has been addressed. Are you able to try https://github.com/mack/magic-upload/releases/tag/v1.0.1-beta and tell me if you still run into this issue?

**Comment by Jizzy015** [comment]
It's 2 am here.I try it in the morning.



---Original---
From: "Mackenzie ***@***.***&gt;
Date: Thu, Aug 18, 2022 02:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mack/magic-upload] There was a error when i downloaded the plugins into the plugin folder (Issue #6)




 
Did you download this from the releases page? I haven't released the latest version yet, where I believe this bug has been addressed. Are you able to try https://github.com/mack/magic-upload/releases/tag/v1.0.1-beta and tell me if you still run into this issue?

**Comment by mack** [comment]
Sounds good, will keep my eyes on this issue and we'll get it resolved asap 👍

**Comment by Jizzy015** [comment]
It worked but not really.It's installed and fired by BetterDiscord properly,but I can't upload anything over 8mb,it said that upload error.1.0.0 version couldn't be fired,latest version can't upload things.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mack/magic-upload"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月18日(星期四) 凌晨2:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mack/magic-upload] There was a error when i downloaded the plugins into the plugin folder (Issue #6)





 
Did you download this from the releases page? I haven't released the latest version yet, where I believe this bug has been addressed. Are you able to try https://github.com/mack/magic-upload/releases/tag/v1.0.1-beta and tell me if you still run into this issue?

**Comment by mack** [comment]
Did you have discord? Would you be able to add me to help debug this? My username is `Mack#4197`

**Comment by Jizzy015** [comment]
added




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mackenzie ***@***.***&gt;; 
发送时间: 2022年8月18日(星期四) 中午11:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mack/magic-upload] There was a error when i downloaded the plugins into the plugin folder (Issue #6)





 
Did you have discord? Would you be able to add me to help debug this? My username is Mack#4197
